color0 #4B4B4D
color1 #A2789F
color2 #50A5D8
color3 #9AA4E2
color4 #E2AFDA
color5 #BEE0FB
color6 #FAEBFD
color7 #F4EDF6
color8 #ABA6AC
color9 #A2789F
color10 #50A5D8
color11 #9AA4E2
color12 #E2AFDA
color13 #BEE0FB
color14 #FAEBFD
color15 #F4EDF6
cursor #A7CFEB