
$background = rgba(17130bff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(353027ff)

$inverse_primary = rgba(7b580dff)

$inverse_surface = rgba(ece1d4ff)

$on_background = rgba(ece1d4ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(422d00ff)

$on_primary_container = rgba(ffdea8ff)

$on_primary_fixed = rgba(271900ff)

$on_primary_fixed_variant = rgba(5e4200ff)

$on_secondary = rgba(3c2e15ff)

$on_secondary_container = rgba(f7dfbbff)

$on_secondary_fixed = rgba(251a04ff)

$on_secondary_fixed_variant = rgba(54442aff)

$on_surface = rgba(ece1d4ff)

$on_surface_variant = rgba(d1c5b4ff)

$on_tertiary = rgba(203619ff)

$on_tertiary_container = rgba(cfebc1ff)

$on_tertiary_fixed = rgba(0b2006ff)

$on_tertiary_fixed_variant = rgba(364d2eff)

$outline = rgba(9a8f80ff)

$outline_variant = rgba(4e4639ff)

$primary = rgba(eebf6dff)

$primary_container = rgba(5e4200ff)

$primary_fixed = rgba(ffdea8ff)

$primary_fixed_dim = rgba(eebf6dff)

$scrim = rgba(000000ff)

$secondary = rgba(dac3a0ff)

$secondary_container = rgba(54442aff)

$secondary_fixed = rgba(f7dfbbff)

$secondary_fixed_dim = rgba(dac3a0ff)

$shadow = rgba(000000ff)

$source_color = rgba(dbab52ff)

$surface = rgba(17130bff)

$surface_bright = rgba(3e382fff)

$surface_container = rgba(241f17ff)

$surface_container_high = rgba(2f2921ff)

$surface_container_highest = rgba(3a342bff)

$surface_container_low = rgba(201b13ff)

$surface_container_lowest = rgba(120e07ff)

$surface_dim = rgba(17130bff)

$surface_tint = rgba(eebf6dff)

$surface_variant = rgba(4e4639ff)

$tertiary = rgba(b3cea6ff)

$tertiary_container = rgba(364d2eff)

$tertiary_fixed = rgba(cfebc1ff)

$tertiary_fixed_dim = rgba(b3cea6ff)



$background_raw = 17130b

$error_raw = ffb4ab

$error_container_raw = 93000a

$inverse_on_surface_raw = 353027

$inverse_primary_raw = 7b580d

$inverse_surface_raw = ece1d4

$on_background_raw = ece1d4

$on_error_raw = 690005

$on_error_container_raw = ffdad6

$on_primary_raw = 422d00

$on_primary_container_raw = ffdea8

$on_primary_fixed_raw = 271900

$on_primary_fixed_variant_raw = 5e4200

$on_secondary_raw = 3c2e15

$on_secondary_container_raw = f7dfbb

$on_secondary_fixed_raw = 251a04

$on_secondary_fixed_variant_raw = 54442a

$on_surface_raw = ece1d4

$on_surface_variant_raw = d1c5b4

$on_tertiary_raw = 203619

$on_tertiary_container_raw = cfebc1

$on_tertiary_fixed_raw = 0b2006

$on_tertiary_fixed_variant_raw = 364d2e

$outline_raw = 9a8f80

$outline_variant_raw = 4e4639

$primary_raw = eebf6d

$primary_container_raw = 5e4200

$primary_fixed_raw = ffdea8

$primary_fixed_dim_raw = eebf6d

$scrim_raw = 000000

$secondary_raw = dac3a0

$secondary_container_raw = 54442a

$secondary_fixed_raw = f7dfbb

$secondary_fixed_dim_raw = dac3a0

$shadow_raw = 000000

$source_color_raw = dbab52

$surface_raw = 17130b

$surface_bright_raw = 3e382f

$surface_container_raw = 241f17

$surface_container_high_raw = 2f2921

$surface_container_highest_raw = 3a342b

$surface_container_low_raw = 201b13

$surface_container_lowest_raw = 120e07

$surface_dim_raw = 17130b

$surface_tint_raw = eebf6d

$surface_variant_raw = 4e4639

$tertiary_raw = b3cea6

$tertiary_container_raw = 364d2e

$tertiary_fixed_raw = cfebc1

$tertiary_fixed_dim_raw = b3cea6
