# Set your monitors up if you need a different mode than the default chosen.

# Example:
monitor = DP-1, 2560x1440@165, auto, auto, vrr, 1
#        name ^    mode ^      position ^     ^ scale 

# If you need to find the name, or mode, execute `hyprctl monitors all` in the terminal.
